name: Build nRF91 1NCE Demos

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  NCS_VERSION: v2.8.0
  NCE_REVISION: main
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
  ZEPHYR_SDK_INSTALL_DIR: /root/ncs/toolchains/b81a7cd864/opt/zephyr-sdk

  DEMOS: nce_udp_demo nce_coap_demo plugin_system/nce_debug_memfault_demo plugin_system/nce_fota_mender_demo

jobs:

  build_and_upload:
    runs-on: ubuntu-22.04
    container:
      image: mtalatcise/nce-nrf:v2.8.0
      options: --workdir /workdir/nce
    defaults:
      run:
        working-directory: /workdir/nce
    strategy:
      matrix:
        board: [thingy91/nrf9160, nrf9160dk/nrf9160, nrf9151dk/nrf9151]
    steps:
      - name: Checkout release code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Overlay release code into workspace
        run: |
          echo "Copying release code into workspace"
          mkdir -p /workdir/nce/blueprint-zephyr
          cp -rv ${GITHUB_WORKSPACE}/* /workdir/nce/blueprint-zephyr/
          cp -rv ${GITHUB_WORKSPACE}/.[!.]* /workdir/nce/blueprint-zephyr/ || true

      - name: Prepare artifacts folder
        run: mkdir -p /workdir/artifacts

      - name: Build demos
        run: |
          cd blueprint-zephyr
          BOARD="${{ matrix.board }}"
          BOARD_FOLDER=$(echo "$BOARD" | tr '/' '_')
          ARTIFACT_DIR="/workdir/artifacts/$BOARD_FOLDER"
          mkdir -p "$ARTIFACT_DIR"
          
          for DEMO in $DEMOS; do
            DEMO_NAME=$(basename "$DEMO")
            BUILD_DIR="/workdir/nce/build_${DEMO_NAME}_${BOARD_FOLDER}"
            DEMO_ARTIFACT_DIR="$ARTIFACT_DIR/$DEMO_NAME"
            mkdir -p "$DEMO_ARTIFACT_DIR"

            if [ "$DEMO" = "plugin_system/nce_fota_mender_demo" ]; then
              # ---------------------------
              # Build version 1
              # ---------------------------
              BUILD_DIR_V1="${BUILD_DIR}_v1"
              mkdir -p "$BUILD_DIR_V1"
              echo "CONFIG_BOOTLOADER_MCUBOOT=y" > "$BUILD_DIR_V1/mcuboot.overlay"

              echo "Building $DEMO version 1 (original prj.conf)"
              west build --build-dir "$BUILD_DIR_V1" "$DEMO" -b "$BOARD/ns" \
                -DOVERLAY_CONFIG="$BUILD_DIR_V1/mcuboot.overlay" \
                -- -DNCS_TOOLCHAIN_VERSION=NONE -DCONF_FILE="prj.conf"

              cp "$BUILD_DIR_V1/$DEMO_NAME/zephyr/zephyr.signed.hex" "$DEMO_ARTIFACT_DIR/${DEMO_NAME}.hex"
              cp "$BUILD_DIR_V1/$DEMO_NAME/zephyr/zephyr.signed.bin" "$DEMO_ARTIFACT_DIR/app_update_v1.bin"

              echo "Creating version 1 .mender"
              mender-artifact write module-image -t "$BOARD_FOLDER" \
                -o "$DEMO_ARTIFACT_DIR/v1.mender" \
                -T release-v1 -n release-v1 \
                -f "$DEMO_ARTIFACT_DIR/app_update_v1.bin" \
                --compression none

              # ---------------------------
              # Build version 2
              # ---------------------------
              sed -i 's/CONFIG_APPLICATION_VERSION=1/CONFIG_APPLICATION_VERSION=2/' "$DEMO/prj.conf"
              sed -i 's/CONFIG_ARTIFACT_NAME="release-v1"/CONFIG_ARTIFACT_NAME="release-v2"/' "$DEMO/prj.conf"

              BUILD_DIR_V2="${BUILD_DIR}_v2"
              mkdir -p "$BUILD_DIR_V2"
              echo "CONFIG_BOOTLOADER_MCUBOOT=y" > "$BUILD_DIR_V2/mcuboot.overlay"

              echo "Building $DEMO version 2 (modified prj.conf)"
              west build --build-dir "$BUILD_DIR_V2" "$DEMO" -b "$BOARD/ns" \
                -DOVERLAY_CONFIG="$BUILD_DIR_V2/mcuboot.overlay" \
                -- -DNCS_TOOLCHAIN_VERSION=NONE -DCONF_FILE="prj.conf"

              cp "$BUILD_DIR_V2/$DEMO_NAME/zephyr/zephyr.signed.bin" "$DEMO_ARTIFACT_DIR/app_update_v2.bin"

              echo "Creating version 2 .mender"
              mender-artifact write module-image -t "$BOARD_FOLDER" \
                -o "$DEMO_ARTIFACT_DIR/v2.mender" \
                -T release-v2 -n release-v2 \
                -f "$DEMO_ARTIFACT_DIR/app_update_v2.bin" \
                --compression none

              echo "Restoring original prj.conf"
              git checkout -- "$DEMO/prj.conf"

            else
              # Normal demos
              mkdir -p "$BUILD_DIR"
              echo "CONFIG_BOOTLOADER_MCUBOOT=y" > "$BUILD_DIR/mcuboot.overlay"

              echo "Building $DEMO"
              west build --build-dir "$BUILD_DIR" "$DEMO" -b "$BOARD/ns" \
                -DOVERLAY_CONFIG="$BUILD_DIR/mcuboot.overlay" \
                -- -DNCS_TOOLCHAIN_VERSION=NONE -DCONF_FILE="prj.conf"

              cp "$BUILD_DIR/$DEMO_NAME/zephyr/zephyr.signed.hex" "$DEMO_ARTIFACT_DIR/${DEMO_NAME}.hex"
            fi
          done

      - name: Create zip per board
        run: |
          BOARD_FOLDER=$(echo "${{ matrix.board }}" | tr '/' '_')
          cd /workdir/artifacts/$BOARD_FOLDER
          zip -r /workdir/artifacts/${BOARD_FOLDER}.zip .
          echo "Created zip: /workdir/artifacts/${BOARD_FOLDER}.zip"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: /workdir/artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
