name: Build nRF91 1NCE Demos

on:
  release:
    types: [created]

env:
  NCS_VERSION: v2.8.0
  NCE_REVISION: main
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
  ZEPHYR_SDK_INSTALL_DIR: /workdir/ncs/toolchains/b81a7cd864/opt/zephyr-sdk
  DEMOS: nce_udp_demo plugin_system/nce_debug_memfault_demo

jobs:

  build:
    runs-on: ubuntu-22.04
    container:
      image: mtalatcise/nce-nrf:v2.8.0
      options: --workdir /workdir/nce
    defaults:
      run:
        working-directory: /workdir/nce
    strategy:
      matrix:
        board: [thingy91/nrf9160]
    steps:
      - name: Checkout release code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
          path: /workdir/nce

      - name: Prepare artifacts folder
        run: mkdir -p /workdir/artifacts

      - name: Build all demos for board
        run: |
          BOARD_SAFE=$(echo "${{ matrix.board }}" | tr '/' '_')
          ARTIFACT_DIR="/workdir/artifacts/$BOARD_SAFE"
          mkdir -p "$ARTIFACT_DIR"

          for DEMO in $DEMOS; do
            BUILD_DIR="/workdir/nce/build_${DEMO}_${BOARD_SAFE}"
            echo "Building $DEMO for ${{ matrix.board }}"
            west build --build-dir "$BUILD_DIR" "$DEMO" -b "${{ matrix.board }}/ns"

            cp "$BUILD_DIR/$DEMO/zephyr/zephyr.bin" "$ARTIFACT_DIR/${DEMO}.bin"
          done

      - name: Create zip per board
        run: |
          BOARD_SAFE=$(echo "${{ matrix.board }}" | tr '/' '_')
          cd /workdir/artifacts/$BOARD_SAFE
          zip -r /workdir/artifacts/${BOARD_SAFE}.zip .

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: /workdir/artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}